### PR TITLE
Fixing code-check compliance

### LINKED ISSUE #18: files_locking app does not pass occ app:check-code
### Steps to reproduce
1. Install 8.1 enterprise
2. invoke occ app:check-code
### Expected behaviour

The app passes the check
### Actual behaviour

The app fails the check:

```

[32mAnalysing /var/www/html/owncloud/apps/files_locking/tests/LockingWrapperTest.php[39m
 5 errors
    [37;41mline   36: OC_User - static method call on private class[39;49m
    [37;41mline   37: OC_User - static method call on private class[39;49m
    [37;41mline   40: OC_User - static method call on private class[39;49m
    [37;41mline   41: OC_User - static method call on private class[39;49m
    [37;41mline   42: OC_User - static method call on private class[39;49m
[32mAnalysing /var/www/html/owncloud/apps/files_locking/tests/LockTest.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_locking/tests/bootstrap.php[39m
 1 errors
    [37;41mline   11: OC_Hook - static method call on private class[39;49m
[32mAnalysing /var/www/html/owncloud/apps/files_locking/lib/lock.php[39m
 46 errors
    [37;41mline   78: OC_Log - static method call on private class[39;49m
    [37;41mline   78: OC_Log - used to fetch a const from[39;49m
    [37;41mline   92: OC_Log - used to fetch a const from[39;49m
    [37;41mline   92: OC_Log - static method call on private class[39;49m
    [37;41mline   97: OC_Log - used to fetch a const from[39;49m
    [37;41mline   97: OC_Log - static method call on private class[39;49m
    [37;41mline  104: OC_Log - static method call on private class[39;49m
    [37;41mline  104: OC_Log - used to fetch a const from[39;49m
    [37;41mline  111: OC_Log - used to fetch a const from[39;49m
    [37;41mline  111: OC_Log - static method call on private class[39;49m
    [37;41mline  126: OC_Log - used to fetch a const from[39;49m
    [37;41mline  126: OC_Log - static method call on private class[39;49m
    [37;41mline  142: OC_Log - used to fetch a const from[39;49m
    [37;41mline  142: OC_Log - static method call on private class[39;49m
    [37;41mline  158: OC_Log - used to fetch a const from[39;49m
    [37;41mline  158: OC_Log - static method call on private class[39;49m
    [37;41mline  164: OC_Log - used to fetch a const from[39;49m
    [37;41mline  164: OC_Log - static method call on private class[39;49m
    [37;41mline  170: OC_Log - static method call on private class[39;49m
    [37;41mline  170: OC_Log - used to fetch a const from[39;49m
    [37;41mline  185: OC_Log - used to fetch a const from[39;49m
    [37;41mline  185: OC_Log - static method call on private class[39;49m
    [37;41mline  189: OC_Log - used to fetch a const from[39;49m
    [37;41mline  189: OC_Log - static method call on private class[39;49m
    [37;41mline  194: OC_Log - static method call on private class[39;49m
    [37;41mline  194: OC_Log - used to fetch a const from[39;49m
    [37;41mline  197: OC_Log - used to fetch a const from[39;49m
    [37;41mline  197: OC_Log - static method call on private class[39;49m
    [37;41mline  206: OC_Log - used to fetch a const from[39;49m
    [37;41mline  206: OC_Log - static method call on private class[39;49m
    [37;41mline  211: OC_Log - used to fetch a const from[39;49m
    [37;41mline  211: OC_Log - static method call on private class[39;49m
    [37;41mline  215: OC_Log - used to fetch a const from[39;49m
    [37;41mline  215: OC_Log - static method call on private class[39;49m
    [37;41mline  250: OC_Log - used to fetch a const from[39;49m
    [37;41mline  250: OC_Log - static method call on private class[39;49m
    [37;41mline  327: OC_Log - static method call on private class[39;49m
    [37;41mline  327: OC_Log - used to fetch a const from[39;49m
    [37;41mline  331: OC_Log - used to fetch a const from[39;49m
    [37;41mline  331: OC_Log - static method call on private class[39;49m
    [37;41mline  340: OC_Log - used to fetch a const from[39;49m
    [37;41mline  340: OC_Log - static method call on private class[39;49m
    [37;41mline  343: OC_Log - static method call on private class[39;49m
    [37;41mline  343: OC_Log - used to fetch a const from[39;49m
    [37;41mline  350: OC_Log - used to fetch a const from[39;49m
    [37;41mline  350: OC_Log - static method call on private class[39;49m
[32mAnalysing /var/www/html/owncloud/apps/files_locking/lib/lockingwrapper.php[39m
 0 errors
[32mAnalysing /var/www/html/owncloud/apps/files_locking/appinfo/app.php[39m
 0 errors
[37;41mApp is not compliant[39;49m

```
### Server configuration

Ubuntu 14.04
PHP 5.5.9
ownCloud Enterprise Edition 8.1 alpha 1 (daily) Build:2015-04-16T03:08:13+00:00 f50798a674bf223e1c8015b9a27287b2ac6c9f1a

### PR DESCRIPTION
**Pull request by th3fallen**
Resolves https://github.com/owncloud/files_locking/issues/18

### CODE REVIEW

File: lib/lock.php [hunk 1]
```diff
@@ -62,6 +65,7 @@ class Lock {
 	 */
 	public function __construct($path) {
 		$this->path = Filesystem::normalizePath($path, true, true);
+		$this->log = \OC::$server->getLogger();
```
Comment (th3fallen) [inline lib/lock.php:68]: Should be injected but since this is instantiated via a wrapper wasn't sure the best way to do that or if it was possible...

File: tests/LockingWrapperTest.php [hunk 2]
```diff
@@ -33,13 +33,6 @@ protected function setup() {
 		parent::setUp();
 
 		App::checkAppEnabled('files_locking');
-		OC_User::clearBackends();
```
Comment (th3fallen) [inline tests/LockingWrapperTest.php:36]: Tests ran fine on my end without these, and $this->user was never even used in these tests...

**Comment by th3fallen** [comment]
@PVince81 @DeepDiver1975 @LukasReschke

**Comment by PVince81** [comment]
Code change looks good :+1:

**Comment by LukasReschke** [comment]
:+1:
